package com.vfit.modules.workout.entity;

import com.vfit.modules.user.entity.User;
import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "workout_plan")
@EntityListeners(AuditingEntityListener.class)
public class WorkoutPlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "plan_id")
    private Long planId;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "template_id")
    private WorkoutTemplate template;

    @Column(name = "plan_name", nullable = false, length = 100)
    private String planName;

    @Column(name = "goal_category", length = 50)
    private String goalCategory;

    @Column(name = "schedule_calendar", length = 50)
    private String scheduleCalendar;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @OneToMany(mappedBy = "workoutPlan",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.EAGER)
    private List<Exercise> exercises = new ArrayList<>();

    // Constructors
    public WorkoutPlan() {}

    // Getters
    public Long getPlanId() { return planId; }
    public User getUser() { return user; }
    public WorkoutTemplate getTemplate() { return template; }
    public String getPlanName() { return planName; }
    public String getGoalCategory() { return goalCategory; }
    public String getScheduleCalendar() { return scheduleCalendar; }
    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public List<Exercise> getExercises() { return exercises; }

    // Setters
    public void setPlanId(Long planId) { this.planId = planId; }
    public void setUser(User user) { this.user = user; }
    public void setTemplate(WorkoutTemplate template) { this.template = template; }
    public void setPlanName(String planName) { this.planName = planName; }
    public void setGoalCategory(String goalCategory) { this.goalCategory = goalCategory; }
    public void setScheduleCalendar(String scheduleCalendar) { this.scheduleCalendar = scheduleCalendar; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    public void setExercises(List<Exercise> exercises) { this.exercises = exercises; }
}