package com.vfit.modules.diet.dto;

import java.time.LocalDateTime;
import java.util.List;

public class DietPlanDto {

    private Long dietPlanId;
    private String planName;
    private String dietType;
    private String scheduleCalendar;
    private Integer targetCalories;
    private Boolean isAutoGenerated;
    private LocalDateTime createdAt;
    private List<MealDto> meals;

    // Constructors
    public DietPlanDto() {}

    // Getters
    public Long getDietPlanId() { return dietPlanId; }
    public String getPlanName() { return planName; }
    public String getDietType() { return dietType; }
    public String getScheduleCalendar() { return scheduleCalendar; }
    public Integer getTargetCalories() { return targetCalories; }
    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public List<MealDto> getMeals() { return meals; }

    // Setters
    public void setDietPlanId(Long dietPlanId) { this.dietPlanId = dietPlanId; }
    public void setPlanName(String planName) { this.planName = planName; }
    public void setDietType(String dietType) { this.dietType = dietType; }
    public void setScheduleCalendar(String scheduleCalendar) { this.scheduleCalendar = scheduleCalendar; }
    public void setTargetCalories(Integer targetCalories) { this.targetCalories = targetCalories; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public void setMeals(List<MealDto> meals) { this.meals = meals; }
}