package com.vfit.modules.workout.service;

import com.vfit.modules.user.entity.Profile;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.ProfileRepository;
import com.vfit.modules.user.repository.UserRepository;
import com.vfit.modules.workout.dto.WorkoutPlanDto;
import com.vfit.modules.workout.entity.Exercise;
import com.vfit.modules.workout.entity.ExerciseLibrary;
import com.vfit.modules.workout.entity.WorkoutPlan;
import com.vfit.modules.workout.repository.ExerciseLibraryRepository;
import com.vfit.modules.workout.repository.WorkoutPlanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class AutoWorkoutGeneratorService {

    @Autowired private UserRepository userRepository;
    @Autowired private ProfileRepository profileRepository;
    @Autowired private WorkoutPlanRepository workoutPlanRepository;
    @Autowired private ExerciseLibraryRepository exerciseLibraryRepository;
    @Autowired private WorkoutService workoutService;

    // UC-07: Auto-generate workout plan
    @Transactional
    public WorkoutPlanDto generateWorkoutPlan(Long userId) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Profile profile = profileRepository.findByUser_UserId(userId)
                .orElseThrow(() -> new RuntimeException("Please complete your profile first"));

        if (profile.getFitnessGoal() == null || profile.getActivityLevel() == null) {
            throw new RuntimeException("Fitness goal and activity level are required in your profile");
        }

        // Derive training level from age, BMI, and activity level combined
        String trainingLevel = deriveTrainingLevel(
                profile.getActivityLevel(),
                profile.getAge(),
                profile.getWeight(),
                profile.getHeight()
        );

        System.out.println("=== Auto Workout Generator ===");
        System.out.println("Goal        : " + profile.getFitnessGoal());
        System.out.println("Activity    : " + profile.getActivityLevel());
        System.out.println("Age         : " + profile.getAge());
        System.out.println("Weight      : " + profile.getWeight() + " kg");
        System.out.println("Height      : " + profile.getHeight() + " cm");
        System.out.println("BMI         : " + calculateBmi(profile.getWeight(), profile.getHeight()));
        System.out.println("TrainingLvl : " + trainingLevel);

        WorkoutPlan plan = new WorkoutPlan();
        plan.setUser(user);
        plan.setPlanName("Auto-Generated: " + formatLabel(profile.getFitnessGoal()));
        plan.setGoalCategory(profile.getFitnessGoal());
        plan.setScheduleCalendar("WEEKLY");
        plan.setIsAutoGenerated(true);

        List<Exercise> exercises = buildWeeklyPlan(plan, profile, trainingLevel);

        if (exercises.isEmpty()) {
            throw new RuntimeException("No exercises available. Please contact admin.");
        }

        plan.setExercises(exercises);
        WorkoutPlan saved = workoutPlanRepository.save(plan);
        return workoutService.mapToDto(saved);
    }

    // ─────────────────────────────────────────────────────────────────────
    // CORE PLAN BUILDER
    // Each goal gets its own science-backed weekly split.
    // ─────────────────────────────────────────────────────────────────────

    private List<Exercise> buildWeeklyPlan(WorkoutPlan plan, Profile profile,
                                            String trainingLevel) {

        String goal         = profile.getFitnessGoal();
        String activityLevel = profile.getActivityLevel();
        int daysPerWeek     = getDaysPerWeek(activityLevel);
        List<Exercise> exercises = new ArrayList<>();

        switch (goal.toUpperCase()) {

            case "MUSCLE_GAIN":
                exercises = buildMusclePlan(plan, trainingLevel, daysPerWeek);
                break;

            case "WEIGHT_LOSS":
                exercises = buildWeightLossPlan(plan, trainingLevel, daysPerWeek,
                        profile.getWeight(), profile.getHeight());
                break;

            case "ENDURANCE":
                exercises = buildEndurancePlan(plan, trainingLevel, daysPerWeek);
                break;

            case "MAINTAIN_FITNESS":
            default:
                exercises = buildMaintenancePlan(plan, trainingLevel, daysPerWeek);
                break;
        }

        return exercises;
    }

    // ─── MUSCLE GAIN: Push / Pull / Legs split ───────────────────────────
    // Science: compound + isolation, progressive overload rep ranges (6-12)
    private List<Exercise> buildMusclePlan(WorkoutPlan plan, String level, int days) {
        List<Exercise> result = new ArrayList<>();

        // Push muscles: chest, shoulders, triceps
        List<String> pushGroups  = Arrays.asList("chest", "shoulders", "triceps");
        // Pull muscles: back, biceps, traps
        List<String> pullGroups  = Arrays.asList("back", "biceps", "traps");
        // Leg day: quads, hamstrings, glutes, calves
        List<String> legGroups   = Arrays.asList("quads", "hamstrings", "glutes", "calves");
        // Core added to all days
        List<String> coreGroups  = Arrays.asList("abs", "lowerback");

        // Day pattern based on days/week
        // 3 days: Push, Pull, Legs
        // 4 days: Push, Pull, Legs, Upper (repeat)
        // 5 days: Push, Pull, Legs, Push, Pull
        String[] dayTypes;
        if (days <= 3) {
            dayTypes = new String[]{"PUSH", "PULL", "LEGS"};
        } else if (days == 4) {
            dayTypes = new String[]{"PUSH", "PULL", "LEGS", "UPPER"};
        } else {
            dayTypes = new String[]{"PUSH", "PULL", "LEGS", "PUSH", "PULL"};
        }

        for (int d = 0; d < days; d++) {
            int day = d + 1;
            String dayType = dayTypes[d % dayTypes.length];
            List<String> targetGroups;

            switch (dayType) {
                case "PUSH":  targetGroups = pushGroups; break;
                case "PULL":  targetGroups = pullGroups; break;
                case "UPPER": targetGroups = concat(pushGroups, pullGroups); break;
                default:      targetGroups = legGroups; break;
            }

            // Get exercises for target muscle groups at the right level
            List<ExerciseLibrary> pool = exerciseLibraryRepository
                    .findByMuscleGroupIn(targetGroups)
                    .stream()
                    .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                    .collect(Collectors.toList());

            if (pool.isEmpty()) {
                pool = exerciseLibraryRepository.findByMuscleGroupIn(targetGroups);
            }

            // Add core exercises to every session
            List<ExerciseLibrary> corePool = exerciseLibraryRepository
                    .findByMuscleGroupIn(coreGroups)
                    .stream()
                    .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                    .collect(Collectors.toList());

            // Pick 4 main exercises + 1 core
            List<ExerciseLibrary> selected = pickDistinct(pool, 4, d);
            if (!corePool.isEmpty()) {
                selected.add(corePool.get(d % corePool.size()));
            }

            for (ExerciseLibrary lib : selected) {
                result.add(buildExercise(plan, lib, day, 4, 10, 60));
            }

            System.out.println("Day " + day + " [" + dayType + "]: "
                    + selected.stream().map(ExerciseLibrary::getExerciseName)
                    .collect(Collectors.joining(", ")));
        }

        return result;
    }

    // ─── WEIGHT LOSS: Cardio + Full-Body circuits ────────────────────────
    // Science: higher reps, shorter rest, mix cardio + resistance = max EPOC
    private List<Exercise> buildWeightLossPlan(WorkoutPlan plan, String level,
                                               int days, Float weight, Float height) {
        List<Exercise> result = new ArrayList<>();

        float bmi = calculateBmi(weight, height);

        // High BMI → lower impact exercises to protect joints
        boolean highImpact = bmi < 30;

        List<ExerciseLibrary> cardioPool = exerciseLibraryRepository.findByCategory("Cardio")
                .stream()
                .filter(e -> highImpact || isLowImpact(e.getExerciseName()))
                .collect(Collectors.toList());

        if (cardioPool.isEmpty()) {
            cardioPool = exerciseLibraryRepository.findByCategory("Cardio");
        }

        List<String> fullBodyGroups = Arrays.asList("chest", "back", "quads",
                "shoulders", "abs");
        List<ExerciseLibrary> strengthPool = exerciseLibraryRepository
                .findByMuscleGroupIn(fullBodyGroups)
                .stream()
                .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                .collect(Collectors.toList());

        if (strengthPool.isEmpty()) {
            strengthPool = exerciseLibraryRepository.findByMuscleGroupIn(fullBodyGroups);
        }

        // Alternate cardio and circuit days
        for (int d = 0; d < days; d++) {
            int day = d + 1;
            boolean isCardioDay = (d % 2 == 0);

            if (isCardioDay) {
                // Pure cardio session
                List<ExerciseLibrary> selected = pickDistinct(cardioPool, 3, d);
                for (ExerciseLibrary lib : selected) {
                    result.add(buildExercise(plan, lib, day, 3, 15, 45));
                }
                System.out.println("Day " + day + " [CARDIO]: "
                        + selected.stream().map(ExerciseLibrary::getExerciseName)
                        .collect(Collectors.joining(", ")));
            } else {
                // Circuit: 2 cardio + 3 strength
                List<ExerciseLibrary> cardio   = pickDistinct(cardioPool, 2, d);
                List<ExerciseLibrary> strength = pickDistinct(strengthPool, 3, d);
                for (ExerciseLibrary lib : cardio) {
                    result.add(buildExercise(plan, lib, day, 3, 12, 45));
                }
                for (ExerciseLibrary lib : strength) {
                    result.add(buildExercise(plan, lib, day, 3, 15, 45));
                }
                System.out.println("Day " + day + " [CIRCUIT]: "
                        + concat(cardio, strength).stream()
                        .map(ExerciseLibrary::getExerciseName)
                        .collect(Collectors.joining(", ")));
            }
        }

        return result;
    }

    // ─── ENDURANCE: Cardio-heavy with functional strength ────────────────
    // Science: aerobic base + muscular endurance = high reps low weight
    private List<Exercise> buildEndurancePlan(WorkoutPlan plan, String level, int days) {
        List<Exercise> result = new ArrayList<>();

        List<ExerciseLibrary> cardioPool = exerciseLibraryRepository.findByCategory("Cardio")
                .stream()
                .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                .collect(Collectors.toList());

        if (cardioPool.isEmpty()) {
            cardioPool = exerciseLibraryRepository.findByCategory("Cardio");
        }

        List<String> functionalGroups = Arrays.asList("quads", "hamstrings",
                "glutes", "abs", "back");
        List<ExerciseLibrary> functionalPool = exerciseLibraryRepository
                .findByMuscleGroupIn(functionalGroups)
                .stream()
                .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                .collect(Collectors.toList());

        if (functionalPool.isEmpty()) {
            functionalPool = exerciseLibraryRepository.findByMuscleGroupIn(functionalGroups);
        }

        for (int d = 0; d < days; d++) {
            int day = d + 1;
            boolean isLongCardio = (d % 3 == 0);

            if (isLongCardio) {
                // Long steady-state cardio
                List<ExerciseLibrary> selected = pickDistinct(cardioPool, 2, d);
                for (ExerciseLibrary lib : selected) {
                    result.add(buildExercise(plan, lib, day, 4, 20, 60));
                }
            } else {
                // Mixed: cardio + functional strength
                List<ExerciseLibrary> cardio      = pickDistinct(cardioPool, 2, d);
                List<ExerciseLibrary> functional  = pickDistinct(functionalPool, 3, d);
                for (ExerciseLibrary lib : cardio) {
                    result.add(buildExercise(plan, lib, day, 3, 20, 50));
                }
                for (ExerciseLibrary lib : functional) {
                    result.add(buildExercise(plan, lib, day, 3, 20, 50));
                }
            }
        }

        return result;
    }

    // ─── MAINTAIN FITNESS: Balanced full-body ────────────────────────────
    private List<Exercise> buildMaintenancePlan(WorkoutPlan plan, String level, int days) {
        List<Exercise> result = new ArrayList<>();

        List<String> allGroups = Arrays.asList("chest", "back", "quads",
                "shoulders", "abs", "cardio");
        List<ExerciseLibrary> pool = exerciseLibraryRepository.findAll()
                .stream()
                .filter(e -> matchesDifficulty(e.getDifficultyLevel(), level))
                .collect(Collectors.toList());

        if (pool.isEmpty()) pool = exerciseLibraryRepository.findAll();

        for (int d = 0; d < days; d++) {
            int day = d + 1;
            List<ExerciseLibrary> selected = pickDistinct(pool, 5, d);
            for (ExerciseLibrary lib : selected) {
                result.add(buildExercise(plan, lib, day, 3, 12, 45));
            }
        }

        return result;
    }

    // ─────────────────────────────────────────────────────────────────────
    // HELPER METHODS
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Training level derived from THREE signals:
     * 1. Activity level (primary)
     * 2. Age (older → more conservative)
     * 3. BMI (very high BMI → start at BEGINNER regardless)
     */
    private String deriveTrainingLevel(String activityLevel, Integer age,
                                    Float weight, Float height) {
        float bmi = calculateBmi(weight, height);

        // BMI > 35 (obese class II+) → always BEGINNER for safety
        if (bmi > 35) return "BEGINNER";

        // Age > 60 → cap at INTERMEDIATE
        int a = (age != null) ? age : 25;

        String levelFromActivity;
        if (activityLevel == null) {
            levelFromActivity = "INTERMEDIATE";
        } else {
            switch (activityLevel.toUpperCase()) {
                case "SEDENTARY": levelFromActivity = "BEGINNER";     break;
                case "LIGHT":     levelFromActivity = "BEGINNER";     break;
                case "MODERATE":  levelFromActivity = "INTERMEDIATE"; break;
                case "ACTIVE":    levelFromActivity = "INTERMEDIATE"; break;
                case "VERY_ACTIVE": levelFromActivity = "ADVANCED";   break;
                default:          levelFromActivity = "INTERMEDIATE"; break;
            }
        }

        // Age cap
        if (a > 60 && "ADVANCED".equals(levelFromActivity)) return "INTERMEDIATE";

        return levelFromActivity;
    }

    private float calculateBmi(Float weight, Float height) {
        if (weight == null || height == null || height == 0) return 22f;
        float heightM = height / 100f;
        return weight / (heightM * heightM);
    }

    private boolean matchesDifficulty(String exerciseDifficulty, String targetLevel) {
        if (exerciseDifficulty == null || targetLevel == null) return true;
        if (targetLevel.equals("BEGINNER"))     return exerciseDifficulty.equals("BEGINNER");
        if (targetLevel.equals("INTERMEDIATE")) return !exerciseDifficulty.equals("ADVANCED");
        return true; // ADVANCED can do all
    }

    private boolean isLowImpact(String name) {
        if (name == null) return true;
        String n = name.toLowerCase();
        // Exclude high-impact moves for users with high BMI
        return !n.contains("jump") && !n.contains("sprint") && !n.contains("burpee")
                && !n.contains("box");
    }

    /**
     * Pick N distinct exercises from a pool, using offset to vary across days
     * so each day gets different exercises
     */
    private List<ExerciseLibrary> pickDistinct(List<ExerciseLibrary> pool, int n, int offset) {
        if (pool.isEmpty()) return new ArrayList<>();
        List<ExerciseLibrary> result = new ArrayList<>();
        int size = pool.size();
        for (int i = 0; i < n && i < size; i++) {
            result.add(pool.get((offset * n + i) % size));
        }
        return result;
    }

    private Exercise buildExercise(WorkoutPlan plan, ExerciseLibrary lib,
                                int day, int sets, int reps, int duration) {
        Exercise e = new Exercise();
        e.setWorkoutPlan(plan);
        e.setLibraryExercise(lib);
        e.setDayOfWeek(day);
        e.setSets(sets);
        e.setReps(reps);
        e.setDurationMinutes(duration);
        return e;
    }

    private <T> List<T> concat(List<T> a, List<T> b) {
        List<T> result = new ArrayList<>(a);
        result.addAll(b);
        return result;
    }

    private int getDaysPerWeek(String activityLevel) {
        if (activityLevel == null) return 3;
        switch (activityLevel.toUpperCase()) {
            case "SEDENTARY": return 2;
            case "LIGHT":     return 3;
            case "MODERATE":  return 4;
            case "ACTIVE":    return 5;
            case "VERY_ACTIVE": return 6;
            default:          return 3;
        }
    }

    private String formatLabel(String value) {
        if (value == null) return "Custom";
        String[] words = value.toLowerCase().replace("_", " ").split(" ");
        StringBuilder sb = new StringBuilder();
        for (String word : words) {
            if (sb.length() > 0) sb.append(" ");
            if (!word.isEmpty()) {
                sb.append(Character.toUpperCase(word.charAt(0)));
                sb.append(word.substring(1));
            }
        }
        return sb.toString();
    }
}