package com.vfit.modules.workout.service;

import com.vfit.modules.user.entity.Profile;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.ProfileRepository;
import com.vfit.modules.user.repository.UserRepository;
import com.vfit.modules.workout.dto.WorkoutPlanDto;
import com.vfit.modules.workout.entity.Exercise;
import com.vfit.modules.workout.entity.ExerciseLibrary;
import com.vfit.modules.workout.entity.WorkoutPlan;
import com.vfit.modules.workout.repository.ExerciseLibraryRepository;
import com.vfit.modules.workout.repository.WorkoutPlanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

@Service
public class AutoWorkoutGeneratorService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProfileRepository profileRepository;

    @Autowired
    private WorkoutPlanRepository workoutPlanRepository;

    @Autowired
    private ExerciseLibraryRepository exerciseLibraryRepository;

    @Autowired
    private WorkoutService workoutService;

    // UC-07: Auto-generate workout plan
    @Transactional
    public WorkoutPlanDto generateWorkoutPlan(Long userId) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Profile profile = profileRepository.findByUser_UserId(userId)
                .orElseThrow(() -> new RuntimeException(
                        "Please complete your profile first"));

        // Validate required profile fields
        if (profile.getFitnessGoal() == null || profile.getActivityLevel() == null) {
            throw new RuntimeException(
                    "Fitness goal and activity level are required");
        }

        WorkoutPlan plan = new WorkoutPlan();
        plan.setUser(user);
        plan.setPlanName("Auto-Generated: " + profile.getFitnessGoal());
        plan.setGoalCategory(profile.getFitnessGoal());
        plan.setScheduleCalendar("WEEKLY");
        plan.setIsAutoGenerated(true);

        // Generate exercises based on goal
        List<Exercise> exercises = generateExercisesForGoal(
                plan, profile.getFitnessGoal(), profile.getActivityLevel());

        if (exercises.isEmpty()) {
            throw new RuntimeException(
                    "No exercises available. Please contact admin.");
        }

        plan.setExercises(exercises);
        WorkoutPlan saved = workoutPlanRepository.save(plan);

        return workoutService.mapToDto(saved);
    }

    // private List<Exercise> generateExercisesForGoal(WorkoutPlan plan,
    //                                                 String goal,
    //                                                 String activityLevel) {

    //     List<Exercise> exercises = new ArrayList<>();
    //     String category = mapGoalToCategory(goal);
    //     String difficulty = mapActivityToDifficulty(activityLevel);

    //     // Try to find exercises matching goal and difficulty
    //     List<ExerciseLibrary> libraryExercises = 
    //             exerciseLibraryRepository
    //                     .findByCategoryAndDifficultyLevel(category, difficulty);

    //     // Fallback: get any exercises from category
    //     if (libraryExercises.isEmpty()) {
    //         libraryExercises = exerciseLibraryRepository.findByCategory(category);
    //     }

    //     // Fallback: get all exercises
    //     if (libraryExercises.isEmpty()) {
    //         libraryExercises = exerciseLibraryRepository.findAll();
    //     }

    //     // Create a 3-day workout split
    //     int exercisesPerDay = Math.min(libraryExercises.size() / 3, 5);

    //     for (int day = 1; day <= 3; day++) {
    //         for (int i = 0; i < exercisesPerDay; i++) {
    //             int index = ((day - 1) * exercisesPerDay + i) % libraryExercises.size();
    //             ExerciseLibrary libExercise = libraryExercises.get(index);

    //             Exercise exercise = new Exercise();
    //             exercise.setWorkoutPlan(plan);
    //             exercise.setLibraryExercise(libExercise);
    //             exercise.setDayOfWeek(day);
    //             exercise.setSets(getSetsForGoal(goal));
    //             exercise.setReps(getRepsForGoal(goal));
    //             exercise.setDurationMinutes(30);

    //             exercises.add(exercise);
    //         }
    //     }

    //     return exercises;
    // }

private List<Exercise> generateExercisesForGoal(WorkoutPlan plan,
                                                    String goal,
                                                    String activityLevel) {

        List<Exercise> exercises = new ArrayList<>();
        String category = mapGoalToCategory(goal);
        String difficulty = mapActivityToDifficulty(activityLevel);

        System.out.println(" Generating workout for goal: " + goal);
        System.out.println(" Mapped to category: " + category);
        System.out.println(" Mapped to difficulty: " + difficulty);

        // Try to find exercises matching goal and difficulty
        List<ExerciseLibrary> libraryExercises = 
                exerciseLibraryRepository
                        .findByCategoryAndDifficultyLevel(category, difficulty);

        System.out.println(" Found " + libraryExercises.size() + 
                " exercises for category=" + category + 
                ", difficulty=" + difficulty);

        // Fallback 1: Get any exercises from category (ignore difficulty)
        if (libraryExercises.isEmpty()) {
            System.out.println(" No exact match, trying category only: " + category);
            libraryExercises = exerciseLibraryRepository.findByCategory(category);
            System.out.println(" Found " + libraryExercises.size() + 
                    " exercises for category=" + category);
        }

        // Fallback 2: Get ALL exercises (ignore category and difficulty)
        if (libraryExercises.isEmpty()) {
            System.out.println(" No category match, getting ALL exercises");
            libraryExercises = exerciseLibraryRepository.findAll();
            System.out.println(" Total exercises in database: " + libraryExercises.size());
        }

        // If STILL empty, throw error
        if (libraryExercises.isEmpty()) {
            throw new RuntimeException("No exercises available. Please contact admin.");
        }

        // Create a 3-day workout split
        int totalExercises = libraryExercises.size();
        int exercisesPerDay = Math.max(2, Math.min(totalExercises / 3, 5));

        System.out.println(" Creating 3-day split with " + exercisesPerDay + 
                " exercises per day");

        for (int day = 1; day <= 3; day++) {
            for (int i = 0; i < exercisesPerDay && i < totalExercises; i++) {
                int index = ((day - 1) * exercisesPerDay + i) % totalExercises;
                ExerciseLibrary libExercise = libraryExercises.get(index);

                Exercise exercise = new Exercise();
                exercise.setWorkoutPlan(plan);
                exercise.setLibraryExercise(libExercise);
                exercise.setDayOfWeek(day);
                exercise.setSets(getSetsForGoal(goal));
                exercise.setReps(getRepsForGoal(goal));
                exercise.setDurationMinutes(30);

                exercises.add(exercise);
                
                System.out.println("  Day " + day + ": " + 
                        libExercise.getExerciseName() + 
                        " (" + libExercise.getCategory() + ")");
            }
        }

        System.out.println(" Created " + exercises.size() + " total exercises");
        return exercises;
    }

    private String mapGoalToCategory(String goal) {
        if (goal == null) return "General";

        switch (goal.toUpperCase()) {
            case "WEIGHT_LOSS":
            case "CARDIO":
                return "Cardio";
            case "MUSCLE_GAIN":
            case "STRENGTH":
                return "Strength";
            case "FLEXIBILITY":
                return "Flexibility";
            default:
                return "General";
        }
    }

    private String mapActivityToDifficulty(String activityLevel) {
        if (activityLevel == null) return "INTERMEDIATE";

        switch (activityLevel.toUpperCase()) {
            case "SEDENTARY":
            case "LOW":
                return "BEGINNER";
            case "MODERATE":
                return "INTERMEDIATE";
            case "HIGH":
            case "VERY_HIGH":
                return "ADVANCED";
            default:
                return "INTERMEDIATE";
        }
    }

    private int getSetsForGoal(String goal) {
        if (goal == null) return 3;

        switch (goal.toUpperCase()) {
            case "WEIGHT_LOSS":
                return 3;
            case "MUSCLE_GAIN":
                return 4;
            case "STRENGTH":
                return 5;
            default:
                return 3;
        }
    }

    private int getRepsForGoal(String goal) {
        if (goal == null) return 12;

        switch (goal.toUpperCase()) {
            case "WEIGHT_LOSS":
                return 15;
            case "MUSCLE_GAIN":
                return 10;
            case "STRENGTH":
                return 6;
            default:
                return 12;
        }
    }
}