package com.vfit.modules.workout.service;

import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.UserRepository;
import com.vfit.modules.workout.dto.CreateWorkoutPlanRequest;
import com.vfit.modules.workout.dto.ExerciseDto;
import com.vfit.modules.workout.dto.WorkoutPlanDto;
import com.vfit.modules.workout.entity.Exercise;
import com.vfit.modules.workout.entity.ExerciseLibrary;
import com.vfit.modules.workout.entity.WorkoutPlan;
import com.vfit.modules.workout.repository.ExerciseLibraryRepository;
import com.vfit.modules.workout.repository.WorkoutPlanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class WorkoutService {

    @Autowired
    private WorkoutPlanRepository workoutPlanRepository;

    @Autowired
    private ExerciseLibraryRepository exerciseLibraryRepository;

    @Autowired
    private UserRepository userRepository;

 // UC-04: Get all workout plans for user
    @Transactional(readOnly = true)
    public List<WorkoutPlanDto> getAllWorkoutPlans(Long userId) {
        List<WorkoutPlan> plans = workoutPlanRepository.findByUser_UserId(userId);
        return plans.stream()
                .map(this::mapToDto)
                .collect(Collectors.toList());
    }

    // UC-04: Get single workout plan
    @Transactional(readOnly = true)
    public WorkoutPlanDto getWorkoutPlan(Long userId, Long planId) {
        WorkoutPlan plan = workoutPlanRepository
                .findByPlanIdAndUser_UserId(planId, userId)
                .orElseThrow(() -> new RuntimeException("Workout plan not found"));
        return mapToDto(plan);
    }

    // UC-04: Create manual workout plan
    @Transactional
    public WorkoutPlanDto createWorkoutPlan(Long userId, CreateWorkoutPlanRequest request) {

        // Validate plan name
        if (request.getPlanName() == null || request.getPlanName().trim().isEmpty()) {
            throw new RuntimeException("Plan name is required");
        }

        // Validate exercises list
        if (request.getExercises() == null || request.getExercises().isEmpty()) {
            throw new RuntimeException("At least one exercise is required");
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        WorkoutPlan plan = new WorkoutPlan();
        plan.setUser(user);
        plan.setPlanName(request.getPlanName());
        plan.setGoalCategory(request.getGoalCategory());
        plan.setScheduleCalendar(request.getScheduleCalendar());
        plan.setIsAutoGenerated(false);

        // Add exercises
        List<Exercise> exercises = new ArrayList<>();
        for (ExerciseDto dto : request.getExercises()) {
            Exercise exercise = new Exercise();
            exercise.setWorkoutPlan(plan);

            // Get exercise from library
            if (dto.getLibraryExerciseId() != null) {
                ExerciseLibrary libExercise = exerciseLibraryRepository
                        .findById(dto.getLibraryExerciseId())
                        .orElseThrow(() -> new RuntimeException(
                                "Exercise not found in library"));
                exercise.setLibraryExercise(libExercise);
            }

            exercise.setSets(dto.getSets());
            exercise.setReps(dto.getReps());
            exercise.setDurationMinutes(dto.getDurationMinutes());
            exercise.setDayOfWeek(dto.getDayOfWeek());
            exercises.add(exercise);
        }

        plan.setExercises(exercises);
        WorkoutPlan saved = workoutPlanRepository.save(plan);
        return mapToDto(saved);
    }

    // UC-04: Update workout plan
    @Transactional
    public WorkoutPlanDto updateWorkoutPlan(Long userId, Long planId,
                                            CreateWorkoutPlanRequest request) {

        WorkoutPlan plan = workoutPlanRepository
                .findByPlanIdAndUser_UserId(planId, userId)
                .orElseThrow(() -> new RuntimeException("Workout plan not found"));

        // Update basic info
        if (request.getPlanName() != null) {
            plan.setPlanName(request.getPlanName());
        }
        if (request.getGoalCategory() != null) {
            plan.setGoalCategory(request.getGoalCategory());
        }
        if (request.getScheduleCalendar() != null) {
            plan.setScheduleCalendar(request.getScheduleCalendar());
        }

        // Update exercises if provided
        if (request.getExercises() != null) {
            plan.getExercises().clear();

            List<Exercise> exercises = new ArrayList<>();
            for (ExerciseDto dto : request.getExercises()) {
                Exercise exercise = new Exercise();
                exercise.setWorkoutPlan(plan);

                if (dto.getLibraryExerciseId() != null) {
                    ExerciseLibrary libExercise = exerciseLibraryRepository
                            .findById(dto.getLibraryExerciseId())
                            .orElseThrow(() -> new RuntimeException(
                                    "Exercise not found in library"));
                    exercise.setLibraryExercise(libExercise);
                }

                exercise.setSets(dto.getSets());
                exercise.setReps(dto.getReps());
                exercise.setDurationMinutes(dto.getDurationMinutes());
                exercise.setDayOfWeek(dto.getDayOfWeek());
                exercises.add(exercise);
            }

            plan.getExercises().addAll(exercises);
        }

        WorkoutPlan updated = workoutPlanRepository.save(plan);
        return mapToDto(updated);
    }

    // UC-04: Delete workout plan
    @Transactional
    public void deleteWorkoutPlan(Long userId, Long planId) {
        WorkoutPlan plan = workoutPlanRepository
                .findByPlanIdAndUser_UserId(planId, userId)
                .orElseThrow(() -> new RuntimeException("Workout plan not found"));

        workoutPlanRepository.delete(plan);
    }

    // Get exercise library (for dropdown in UI)
    public List<ExerciseLibrary> getAllExercises() {
        return exerciseLibraryRepository.findAll();
    }

    // Map entity to DTO
    public WorkoutPlanDto mapToDto(WorkoutPlan plan) {
        WorkoutPlanDto dto = new WorkoutPlanDto();
        dto.setPlanId(plan.getPlanId());
        dto.setPlanName(plan.getPlanName());
        dto.setGoalCategory(plan.getGoalCategory());
        dto.setScheduleCalendar(plan.getScheduleCalendar());
        dto.setIsAutoGenerated(plan.getIsAutoGenerated());
        dto.setCreatedAt(plan.getCreatedAt());

        List<ExerciseDto> exerciseDtos = plan.getExercises().stream()
                .map(this::mapExerciseToDto)
                .collect(Collectors.toList());
        dto.setExercises(exerciseDtos);

        return dto;
    }

    public ExerciseDto mapExerciseToDto(Exercise exercise) {
        ExerciseDto dto = new ExerciseDto();
        dto.setExerciseId(exercise.getExerciseId());

        if (exercise.getLibraryExercise() != null) {
            dto.setLibraryExerciseId(exercise.getLibraryExercise().getLibraryExerciseId());
            dto.setExerciseName(exercise.getLibraryExercise().getExerciseName());
            dto.setCategory(exercise.getLibraryExercise().getCategory());
            dto.setMuscleGroup(exercise.getLibraryExercise().getMuscleGroup());
        }

        dto.setSets(exercise.getSets());
        dto.setReps(exercise.getReps());
        dto.setDurationMinutes(exercise.getDurationMinutes());
        dto.setDayOfWeek(exercise.getDayOfWeek());

        return dto;
    }
}