package com.vfit.modules.diet.service;

import com.vfit.modules.diet.dto.CreateDietPlanRequest;
import com.vfit.modules.diet.dto.DietPlanDto;
import com.vfit.modules.diet.dto.MealDto;
import com.vfit.modules.diet.entity.DietPlan;
import com.vfit.modules.diet.entity.FoodLibrary;
import com.vfit.modules.diet.repository.DietPlanRepository;
import com.vfit.modules.diet.repository.FoodLibraryRepository;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class DietServiceTest {

    @Mock private DietPlanRepository dietPlanRepository;
    @Mock private FoodLibraryRepository foodLibraryRepository;
    @Mock private UserRepository userRepository;

    @InjectMocks
    private DietService dietService;

    private User testUser;

    @BeforeEach
    void setUp() {
        testUser = new User();
        testUser.setUserId(1L);
        testUser.setEmail("vraj@example.com");
    }

    // ============================================================
    // UC-05: Create Diet Plan Tests
    // ============================================================
    @Nested
    @DisplayName("UC-05: Create Diet Plan")
    class CreateDietPlanTests {

        @Test
        @DisplayName("DIET-01: Successful diet plan creation")
        void createDietPlan_Success() {
            MealDto mealDto = new MealDto();
            mealDto.setFoodId(5L);
            mealDto.setMealType("BREAKFAST");
            mealDto.setCalories(400);

            CreateDietPlanRequest request = new CreateDietPlanRequest();
            request.setPlanName("Keto Plan");
            request.setDietType("KETO");
            request.setTargetCalories(2000);
            request.setMeals(List.of(mealDto));

            FoodLibrary food = new FoodLibrary();
            food.setFoodId(5L);
            food.setFoodName("Eggs");
            food.setCaloriesPerServing(155);

            when(userRepository.findById(1L)).thenReturn(Optional.of(testUser));
            when(foodLibraryRepository.findById(5L)).thenReturn(Optional.of(food));
            when(dietPlanRepository.save(any(DietPlan.class))).thenAnswer(invocation -> {
                DietPlan plan = invocation.getArgument(0);
                plan.setDietPlanId(100L);
                plan.setCreatedAt(LocalDateTime.now());
                return plan;
            });

            DietPlanDto result = dietService.createDietPlan(1L, request);

            assertNotNull(result);
            assertEquals("Keto Plan", result.getPlanName());
            assertEquals("KETO", result.getDietType());
            assertFalse(result.getIsAutoGenerated());
            verify(dietPlanRepository).save(any(DietPlan.class));
        }

        @Test
        @DisplayName("DIET-02: Empty plan name throws exception")
        void createDietPlan_EmptyName() {
            CreateDietPlanRequest request = new CreateDietPlanRequest();
            request.setPlanName("");
            request.setMeals(List.of(new MealDto()));

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> dietService.createDietPlan(1L, request));

            assertEquals("Plan name is required", ex.getMessage());
        }

        @Test
        @DisplayName("DIET-03: No meals throws exception")
        void createDietPlan_NoMeals() {
            CreateDietPlanRequest request = new CreateDietPlanRequest();
            request.setPlanName("My Diet");
            request.setMeals(Collections.emptyList());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> dietService.createDietPlan(1L, request));

            assertEquals("At least one meal is required", ex.getMessage());
        }

        @Test
        @DisplayName("DIET-04: Non-existent user throws exception")
        void createDietPlan_UserNotFound() {
            MealDto mealDto = new MealDto();
            mealDto.setCalories(300);

            CreateDietPlanRequest request = new CreateDietPlanRequest();
            request.setPlanName("My Diet");
            request.setMeals(List.of(mealDto));

            when(userRepository.findById(999L)).thenReturn(Optional.empty());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> dietService.createDietPlan(999L, request));

            assertEquals("User not found", ex.getMessage());
        }
    }

    // ============================================================
    // UC-05: Get Diet Plans Tests
    // ============================================================
    @Nested
    @DisplayName("UC-05: Get Diet Plans")
    class GetDietPlanTests {

        @Test
        @DisplayName("DIET-05: Get all plans returns list")
        void getAllDietPlans_ReturnsList() {
            DietPlan plan = new DietPlan();
            plan.setDietPlanId(1L);
            plan.setPlanName("Balanced Diet");
            plan.setUser(testUser);
            plan.setMeals(new ArrayList<>());
            plan.setCreatedAt(LocalDateTime.now());

            when(dietPlanRepository.findByUser_UserId(1L)).thenReturn(List.of(plan));

            List<DietPlanDto> results = dietService.getAllDietPlans(1L);

            assertEquals(1, results.size());
            assertEquals("Balanced Diet", results.get(0).getPlanName());
        }

        @Test
        @DisplayName("DIET-06: Non-existent plan throws exception")
        void getDietPlan_NotFound() {
            when(dietPlanRepository.findByDietPlanIdAndUser_UserId(999L, 1L))
                    .thenReturn(Optional.empty());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> dietService.getDietPlan(1L, 999L));

            assertEquals("Diet plan not found", ex.getMessage());
        }
    }
}