package com.vfit.modules.diet.entity;

import com.vfit.modules.user.entity.User;
import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "diet_plan")
@EntityListeners(AuditingEntityListener.class)
public class DietPlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "diet_plan_id")
    private Long dietPlanId;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "template_id")
    private DietTemplate template;

    @Column(name = "plan_name", nullable = false, length = 100)
    private String planName;

    @Column(name = "diet_type", length = 50)
    private String dietType;

    @Column(name = "schedule_calendar", length = 50)
    private String scheduleCalendar;

    @Column(name = "target_calories")
    private Integer targetCalories;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @OneToMany(mappedBy = "dietPlan",
               cascade = CascadeType.ALL,
               orphanRemoval = true,
               fetch = FetchType.EAGER)
    private List<Meal> meals = new ArrayList<>();

    // Constructors
    public DietPlan() {}

    // Getters
    public Long getDietPlanId() { return dietPlanId; }
    public User getUser() { return user; }
    public DietTemplate getTemplate() { return template; }
    public String getPlanName() { return planName; }
    public String getDietType() { return dietType; }
    public String getScheduleCalendar() { return scheduleCalendar; }
    public Integer getTargetCalories() { return targetCalories; }
    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public List<Meal> getMeals() { return meals; }

    // Setters
    public void setDietPlanId(Long dietPlanId) { this.dietPlanId = dietPlanId; }
    public void setUser(User user) { this.user = user; }
    public void setTemplate(DietTemplate template) { this.template = template; }
    public void setPlanName(String planName) { this.planName = planName; }
    public void setDietType(String dietType) { this.dietType = dietType; }
    public void setScheduleCalendar(String scheduleCalendar) { this.scheduleCalendar = scheduleCalendar; }
    public void setTargetCalories(Integer targetCalories) { this.targetCalories = targetCalories; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    public void setMeals(List<Meal> meals) { this.meals = meals; }
}