spring:
  application:
    name: v-fit-backend

  datasource:
    url: jdbc:postgresql://postgres:5432/vfit_db
    username: vfit_user
    password: vfit_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vfit.noreply@gmail.com
    password: gslnmitpnyprdvzl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend-url: http://localhost:3000

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: VFitSecretKeyForJWTTokenGenerationPleaseChangeInProduction2024
  expiration: 86400000
  refresh-expiration: 604800000

external:
  wger:
    api-key: fc12979304e8a65bd110971cc3e72c909d154a70
    base-url: https://wger.de/api/v2
  usda:
    api-key: 6pNuvOkSDCuuSRcLpGLMv3fY99zsfh9rxhGrg7zD
    base-url: https://api.nal.usda.gov/fdc/v1

  openrouter:
    api-key: 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
    base-url: https://openrouter.ai/api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.vfit: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
google:
  client-id: 105127700631-0jikef3c58klcg0f96uki07s6vi4d6m7.apps.googleusercontent.com

