package com.vfit.modules.workout.dto;

import java.time.LocalDateTime;
import java.util.List;

public class WorkoutPlanDto {

    private Long planId;
    private String planName;
    private String goalCategory;
    private String scheduleCalendar;
    private Boolean isAutoGenerated;
    private LocalDateTime createdAt;
    private List<ExerciseDto> exercises;

    // Constructors
    public WorkoutPlanDto() {}

    // Getters
    public Long getPlanId() { return planId; }
    public String getPlanName() { return planName; }
    public String getGoalCategory() { return goalCategory; }
    public String getScheduleCalendar() { return scheduleCalendar; }
    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public List<ExerciseDto> getExercises() { return exercises; }

    // Setters
    public void setPlanId(Long planId) { this.planId = planId; }
    public void setPlanName(String planName) { this.planName = planName; }
    public void setGoalCategory(String goalCategory) { this.goalCategory = goalCategory; }
    public void setScheduleCalendar(String scheduleCalendar) { this.scheduleCalendar = scheduleCalendar; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public void setExercises(List<ExerciseDto> exercises) { this.exercises = exercises; }
}