package com.vfit.modules.workout.service;

import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.UserRepository;
import com.vfit.modules.workout.dto.CreateWorkoutPlanRequest;
import com.vfit.modules.workout.dto.ExerciseDto;
import com.vfit.modules.workout.dto.WorkoutPlanDto;
import com.vfit.modules.workout.entity.Exercise;
import com.vfit.modules.workout.entity.ExerciseLibrary;
import com.vfit.modules.workout.entity.WorkoutPlan;
import com.vfit.modules.workout.repository.ExerciseLibraryRepository;
import com.vfit.modules.workout.repository.WorkoutPlanRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class WorkoutServiceTest {

    @Mock private WorkoutPlanRepository workoutPlanRepository;
    @Mock private ExerciseLibraryRepository exerciseLibraryRepository;
    @Mock private UserRepository userRepository;

    @InjectMocks
    private WorkoutService workoutService;

    private User testUser;

    @BeforeEach
    void setUp() {
        testUser = new User();
        testUser.setUserId(1L);
        testUser.setEmail("vraj@example.com");
    }

    // ============================================================
    // Create Workout Plan Tests
    // ============================================================
    @Nested
    @DisplayName("UC-04: Create Workout Plan")
    class CreateWorkoutPlanTests {

        @Test
        @DisplayName("WRK-01: Successful plan creation with exercises")
        void createWorkoutPlan_Success() {
            ExerciseDto exerciseDto = new ExerciseDto();
            exerciseDto.setLibraryExerciseId(10L);
            exerciseDto.setSets(3);
            exerciseDto.setReps(12);
            exerciseDto.setDayOfWeek(1);

            CreateWorkoutPlanRequest request = new CreateWorkoutPlanRequest();
            request.setPlanName("Strength Training");
            request.setGoalCategory("MUSCLE_GAIN");
            request.setExercises(List.of(exerciseDto));

            ExerciseLibrary libExercise = new ExerciseLibrary();
            libExercise.setLibraryExerciseId(10L);
            libExercise.setExerciseName("Bench Press");
            libExercise.setCategory("Chest");

            when(userRepository.findById(1L)).thenReturn(Optional.of(testUser));
            when(exerciseLibraryRepository.findById(10L)).thenReturn(Optional.of(libExercise));
            when(workoutPlanRepository.save(any(WorkoutPlan.class))).thenAnswer(invocation -> {
                WorkoutPlan plan = invocation.getArgument(0);
                plan.setPlanId(100L);
                plan.setCreatedAt(LocalDateTime.now());
                return plan;
            });

            WorkoutPlanDto result = workoutService.createWorkoutPlan(1L, request);

            assertNotNull(result);
            assertEquals("Strength Training", result.getPlanName());
            assertEquals("MUSCLE_GAIN", result.getGoalCategory());
            assertFalse(result.getIsAutoGenerated());
            verify(workoutPlanRepository).save(any(WorkoutPlan.class));
        }

        @Test
        @DisplayName("WRK-02: Empty plan name throws exception")
        void createWorkoutPlan_EmptyName() {
            CreateWorkoutPlanRequest request = new CreateWorkoutPlanRequest();
            request.setPlanName("");
            request.setExercises(List.of(new ExerciseDto()));

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> workoutService.createWorkoutPlan(1L, request));

            assertEquals("Plan name is required", ex.getMessage());
        }

        @Test
        @DisplayName("WRK-03: No exercises throws exception")
        void createWorkoutPlan_NoExercises() {
            CreateWorkoutPlanRequest request = new CreateWorkoutPlanRequest();
            request.setPlanName("My Plan");
            request.setExercises(Collections.emptyList());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> workoutService.createWorkoutPlan(1L, request));

            assertEquals("At least one exercise is required", ex.getMessage());
        }

        @Test
        @DisplayName("WRK-04: Non-existent user throws exception")
        void createWorkoutPlan_UserNotFound() {
            ExerciseDto exerciseDto = new ExerciseDto();
            exerciseDto.setSets(3);

            CreateWorkoutPlanRequest request = new CreateWorkoutPlanRequest();
            request.setPlanName("My Plan");
            request.setExercises(List.of(exerciseDto));

            when(userRepository.findById(999L)).thenReturn(Optional.empty());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> workoutService.createWorkoutPlan(999L, request));

            assertEquals("User not found", ex.getMessage());
        }
    }

    // ============================================================
    // Get Workout Plans Tests
    // ============================================================
    @Nested
    @DisplayName("UC-04: Get Workout Plans")
    class GetWorkoutPlanTests {

        @Test
        @DisplayName("WRK-05: Get all plans returns list")
        void getAllWorkoutPlans_ReturnsList() {
            WorkoutPlan plan = new WorkoutPlan();
            plan.setPlanId(1L);
            plan.setPlanName("Morning Routine");
            plan.setUser(testUser);
            plan.setExercises(new ArrayList<>());
            plan.setCreatedAt(LocalDateTime.now());

            when(workoutPlanRepository.findByUser_UserId(1L)).thenReturn(List.of(plan));

            List<WorkoutPlanDto> results = workoutService.getAllWorkoutPlans(1L);

            assertEquals(1, results.size());
            assertEquals("Morning Routine", results.get(0).getPlanName());
        }

        @Test
        @DisplayName("WRK-06: Get single plan by ID")
        void getWorkoutPlan_ById() {
            WorkoutPlan plan = new WorkoutPlan();
            plan.setPlanId(1L);
            plan.setPlanName("Leg Day");
            plan.setUser(testUser);
            plan.setExercises(new ArrayList<>());
            plan.setCreatedAt(LocalDateTime.now());

            when(workoutPlanRepository.findByPlanIdAndUser_UserId(1L, 1L))
                    .thenReturn(Optional.of(plan));

            WorkoutPlanDto result = workoutService.getWorkoutPlan(1L, 1L);

            assertEquals("Leg Day", result.getPlanName());
        }

        @Test
        @DisplayName("WRK-07: Non-existent plan throws exception")
        void getWorkoutPlan_NotFound() {
            when(workoutPlanRepository.findByPlanIdAndUser_UserId(999L, 1L))
                    .thenReturn(Optional.empty());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> workoutService.getWorkoutPlan(1L, 999L));

            assertEquals("Workout plan not found", ex.getMessage());
        }
    }

    // ============================================================
    // Delete Workout Plan Tests
    // ============================================================
    @Nested
    @DisplayName("UC-04: Delete Workout Plan")
    class DeleteWorkoutPlanTests {

        @Test
        @DisplayName("WRK-08: Successful delete")
        void deleteWorkoutPlan_Success() {
            WorkoutPlan plan = new WorkoutPlan();
            plan.setPlanId(1L);
            plan.setUser(testUser);

            when(workoutPlanRepository.findByPlanIdAndUser_UserId(1L, 1L))
                    .thenReturn(Optional.of(plan));

            assertDoesNotThrow(() -> workoutService.deleteWorkoutPlan(1L, 1L));
            verify(workoutPlanRepository).delete(plan);
        }

        @Test
        @DisplayName("WRK-09: Delete non-existent plan throws exception")
        void deleteWorkoutPlan_NotFound() {
            when(workoutPlanRepository.findByPlanIdAndUser_UserId(999L, 1L))
                    .thenReturn(Optional.empty());

            RuntimeException ex = assertThrows(RuntimeException.class,
                    () -> workoutService.deleteWorkoutPlan(1L, 999L));

            assertEquals("Workout plan not found", ex.getMessage());
        }
    }
}