// package com.vfit.modules.diet.service;

// import com.vfit.modules.diet.dto.DietPlanDto;
// import com.vfit.modules.diet.entity.DietPlan;
// import com.vfit.modules.diet.entity.FoodLibrary;
// import com.vfit.modules.diet.entity.Meal;
// import com.vfit.modules.diet.repository.DietPlanRepository;
// import com.vfit.modules.diet.repository.FoodLibraryRepository;
// import com.vfit.modules.user.entity.Profile;
// import com.vfit.modules.user.entity.User;
// import com.vfit.modules.user.repository.ProfileRepository;
// import com.vfit.modules.user.repository.UserRepository;
// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.stereotype.Service;
// import org.springframework.transaction.annotation.Transactional;

// import java.util.ArrayList;
// import java.util.List;

// @Service
// public class AutoDietGeneratorService {

//     @Autowired
//     private UserRepository userRepository;

//     @Autowired
//     private ProfileRepository profileRepository;

//     @Autowired
//     private DietPlanRepository dietPlanRepository;

//     @Autowired
//     private FoodLibraryRepository foodLibraryRepository;

//     @Autowired
//     private DietService dietService;

//     // UC-06: Auto-generate diet plan
//     @Transactional
//     public DietPlanDto generateDietPlan(Long userId) {

//         User user = userRepository.findById(userId)
//                 .orElseThrow(() -> new RuntimeException("User not found"));

//         Profile profile = profileRepository.findByUser_UserId(userId)
//                 .orElseThrow(() -> new RuntimeException(
//                         "Please complete your profile first"));

//         if (profile.getFitnessGoal() == null || profile.getDietaryPreference() == null) {
//             throw new RuntimeException(
//                     "Fitness goal and dietary preference are required");
//         }

//         DietPlan plan = new DietPlan();
//         plan.setUser(user);
//         plan.setPlanName("Auto-Generated: " + profile.getFitnessGoal());
//         plan.setDietType(profile.getDietaryPreference());
//         plan.setScheduleCalendar("WEEKLY");
//         plan.setIsAutoGenerated(true);

//         // Calculate target calories based on goal
//         int targetCalories = calculateTargetCalories(
//                 profile.getFitnessGoal(),
//                 profile.getWeight(),
//                 profile.getActivityLevel()
//         );
//         plan.setTargetCalories(targetCalories);

//         System.out.println(" Generating diet for goal: " + profile.getFitnessGoal());
//         System.out.println(" Diet preference: " + profile.getDietaryPreference());
//         System.out.println(" Target calories: " + targetCalories);

//         // Generate meals
//         List<Meal> meals = generateMealsForGoal(
//                 plan,
//                 profile.getDietaryPreference(),
//                 targetCalories
//         );

//         if (meals.isEmpty()) {
//             throw new RuntimeException("No foods available. Please contact admin.");
//         }

//         plan.setMeals(meals);
//         DietPlan saved = dietPlanRepository.save(plan);

//         return dietService.mapToDto(saved);
//     }

//     private List<Meal> generateMealsForGoal(DietPlan plan,
//                                             String dietPreference,
//                                             int targetCalories) {

//         List<Meal> meals = new ArrayList<>();

//         // Get foods from library
//         List<FoodLibrary> foodLibrary = foodLibraryRepository.findAll();

//         if (foodLibrary.isEmpty()) {
//             throw new RuntimeException("Food library is empty");
//         }

//         System.out.println(" Found " + foodLibrary.size() + " foods in library");

//         // Calculate calories per meal (3 meals per day, 7 days)
//         int caloriesPerMeal = targetCalories / 3;

//         String[] mealTypes = {"BREAKFAST", "LUNCH", "DINNER"};

//         // Generate 7 days of meals
//         for (int day = 1; day <= 7; day++) {
//             for (String mealType : mealTypes) {
//                 int foodIndex = ((day - 1) * 3 + meals.size()) % foodLibrary.size();
//                 FoodLibrary food = foodLibrary.get(foodIndex);

//                 Meal meal = new Meal();
//                 meal.setDietPlan(plan);
//                 meal.setFood(food);
//                 meal.setMealType(mealType);
//                 meal.setDayOfWeek(day);
//                 meal.setCalories(food.getCaloriesPerServing());
//                 meal.setProteinGrams(food.getProteinGrams());
//                 meal.setCarbsGrams(food.getCarbsGrams());
//                 meal.setFatsGrams(food.getFatsGrams());

//                 meals.add(meal);

//                 System.out.println("  Day " + day + " - " + mealType + 
//                         ": " + food.getFoodName() + 
//                         " (" + food.getCaloriesPerServing() + " cal)");
//             }
//         }

//         System.out.println(" Created " + meals.size() + " total meals");
//         return meals;
//     }

//     private int calculateTargetCalories(String goal, Float weight, String activityLevel) {
        
//         int baseCalories = 2000;

//         // Adjust based on weight
//         if (weight != null) {
//             baseCalories = (int) (weight * 30);
//         }

//         // Adjust based on activity level
//         if (activityLevel != null) {
//             switch (activityLevel.toUpperCase()) {
//                 case "SEDENTARY":
//                 case "LOW":
//                     baseCalories *= 1.2;
//                     break;
//                 case "MODERATE":
//                     baseCalories *= 1.55;
//                     break;
//                 case "HIGH":
//                 case "VERY_HIGH":
//                     baseCalories *= 1.9;
//                     break;
//             }
//         }

//         // Adjust based on goal
//         if (goal != null) {
//             switch (goal.toUpperCase()) {
//                 case "WEIGHT_LOSS":
//                     baseCalories -= 500;
//                     break;
//                 case "MUSCLE_GAIN":
//                 case "WEIGHT_GAIN":
//                     baseCalories += 500;
//                     break;
//             }
//         }

//         return Math.max(1200, Math.min(baseCalories, 4000));
//     }
// }

package com.vfit.modules.diet.service;

import com.vfit.modules.diet.dto.DietPlanDto;
import com.vfit.modules.diet.entity.DietPlan;
import com.vfit.modules.diet.entity.FoodLibrary;
import com.vfit.modules.diet.entity.Meal;
import com.vfit.modules.diet.repository.DietPlanRepository;
import com.vfit.modules.diet.repository.FoodLibraryRepository;
import com.vfit.modules.user.entity.Profile;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.ProfileRepository;
import com.vfit.modules.user.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class AutoDietGeneratorService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProfileRepository profileRepository;

    @Autowired
    private DietPlanRepository dietPlanRepository;

    @Autowired
    private FoodLibraryRepository foodLibraryRepository;

    @Autowired
    private DietService dietService;

    // UC-06: Auto-generate diet plan
    @Transactional
    public DietPlanDto generateDietPlan(Long userId) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Profile profile = profileRepository.findByUser_UserId(userId)
                .orElseThrow(() -> new RuntimeException(
                        "Please complete your profile first"));

        if (profile.getFitnessGoal() == null || profile.getDietaryPreference() == null) {
            throw new RuntimeException(
                    "Fitness goal and dietary preference are required");
        }

        // Calculate realistic daily calorie target
        int dailyCalories = calculateDailyCalories(
                profile.getFitnessGoal(),
                profile.getWeight(),
                profile.getHeight(),
                profile.getAge(),
                profile.getGender(),
                profile.getActivityLevel()
        );

        DietPlan plan = new DietPlan();
        plan.setUser(user);
        plan.setPlanName("Auto-Generated: " + formatGoalLabel(profile.getFitnessGoal()));
        plan.setDietType(profile.getDietaryPreference());
        plan.setScheduleCalendar("WEEKLY");
        plan.setIsAutoGenerated(true);
        plan.setTargetCalories(dailyCalories);

        System.out.println("Generating diet | goal=" + profile.getFitnessGoal()
                + " | preference=" + profile.getDietaryPreference()
                + " | daily target=" + dailyCalories + " kcal");

        List<Meal> meals = generateMealsForGoal(
                plan,
                profile.getDietaryPreference(),
                dailyCalories
        );

        if (meals.isEmpty()) {
            throw new RuntimeException("No foods available. Please contact admin.");
        }

        plan.setMeals(meals);
        DietPlan saved = dietPlanRepository.save(plan);

        return dietService.mapToDto(saved);
    }

    private List<Meal> generateMealsForGoal(DietPlan plan,
                                            String dietPreference,
                                            int dailyCalories) {

        List<Meal> meals = new ArrayList<>();
        List<FoodLibrary> allFoods = foodLibraryRepository.findAll();

        if (allFoods.isEmpty()) {
            throw new RuntimeException("Food library is empty");
        }

        System.out.println("Food library size: " + allFoods.size());

        // Filter foods based on dietary preference
        List<FoodLibrary> allowedFoods = filterByPreference(allFoods, dietPreference);
        if (allowedFoods.isEmpty()) {
            System.out.println("Warning: preference filter returned 0 foods – using all foods");
            allowedFoods = allFoods;
        }
        System.out.println("Foods after preference filter: " + allowedFoods.size());

        // Separate into meal-type pools
        List<FoodLibrary> breakfastPool = filterByCategory(allowedFoods, "Breakfast");
        List<FoodLibrary> lunchPool     = filterByCategory(allowedFoods, "Lunch");
        List<FoodLibrary> dinnerPool    = filterByCategory(allowedFoods, "Dinner");
        List<FoodLibrary> snackPool     = filterByCategory(allowedFoods, "Snack");

        // Fallback pools if a category is empty after preference filtering
        if (breakfastPool.isEmpty()) breakfastPool = filterByCategory(allFoods, "Breakfast");
        if (lunchPool.isEmpty())     lunchPool     = filterByCategory(allFoods, "Lunch");
        if (dinnerPool.isEmpty())    dinnerPool    = filterByCategory(allFoods, "Dinner");
        if (snackPool.isEmpty())     snackPool     = filterByCategory(allFoods, "Snack");
        // Last-resort: use any allowed food
        if (breakfastPool.isEmpty()) breakfastPool = allowedFoods;
        if (lunchPool.isEmpty())     lunchPool     = allowedFoods;
        if (dinnerPool.isEmpty())    dinnerPool    = allowedFoods;
        if (snackPool.isEmpty())     snackPool     = allowedFoods;

        // Calorie split per meal (must sum to dailyCalories)
        // Breakfast 25% | Lunch 35% | Dinner 30% | Snack 10%
        int breakfastCal = (int) Math.round(dailyCalories * 0.25);
        int lunchCal     = (int) Math.round(dailyCalories * 0.35);
        int dinnerCal    = (int) Math.round(dailyCalories * 0.30);
        int snackCal     = (int) Math.round(dailyCalories * 0.10);

        String[] mealTypes      = {"BREAKFAST", "LUNCH", "DINNER", "SNACK"};
        int[]    mealCalTargets = {breakfastCal, lunchCal, dinnerCal, snackCal};
        List<List<FoodLibrary>> pools = Arrays.asList(
                breakfastPool, lunchPool, dinnerPool, snackPool);

        System.out.println("Daily split: B=" + breakfastCal + " L=" + lunchCal
                + " D=" + dinnerCal + " S=" + snackCal + " | total="
                + (breakfastCal + lunchCal + dinnerCal + snackCal));

        for (int day = 1; day <= 7; day++) {
            int dayTotal = 0;
            for (int m = 0; m < mealTypes.length; m++) {
                List<FoodLibrary> pool = pools.get(m);
                // Rotate through pool across 7 days so meals vary each day
                FoodLibrary food = pool.get((day - 1) % pool.size());

                int calTarget = mealCalTargets[m];

                // Scale macros proportionally to hit the calorie target
                float rawCal = Math.max(food.getCaloriesPerServing(), 1);
                float scale  = (float) calTarget / rawCal;

                Meal meal = new Meal();
                meal.setDietPlan(plan);
                meal.setFood(food);
                meal.setMealType(mealTypes[m]);
                meal.setDayOfWeek(day);
                meal.setCalories(calTarget);
                meal.setProteinGrams(Math.round(food.getProteinGrams() * scale * 10f) / 10f);
                meal.setCarbsGrams( Math.round(food.getCarbsGrams()   * scale * 10f) / 10f);
                meal.setFatsGrams(  Math.round(food.getFatsGrams()    * scale * 10f) / 10f);

                meals.add(meal);
                dayTotal += calTarget;

                System.out.println("  Day " + day + " [" + mealTypes[m] + "]: "
                        + food.getFoodName() + " -> " + calTarget + " cal"
                        + " (P:" + meal.getProteinGrams()
                        + " C:" + meal.getCarbsGrams()
                        + " F:" + meal.getFatsGrams() + ")");
            }
            System.out.println("  Day " + day + " total: " + dayTotal + " / " + dailyCalories + " kcal");
        }

        System.out.println("Created " + meals.size() + " meals (7 days x 4 meals)");
        return meals;
    }

    // ── Calorie Calculation — Real Mifflin-St Jeor using actual profile data ──
    //
    //   Male BMR   = (10 × weight_kg) + (6.25 × height_cm) − (5 × age) + 5
    //   Female BMR = (10 × weight_kg) + (6.25 × height_cm) − (5 × age) − 161
    //   TDEE = BMR × activity multiplier
    //   Adjusted for goal: deficit / surplus / maintenance

    private int calculateDailyCalories(String goal, Float weight, Float height,
                                       Integer age, String gender,
                                       String activityLevel) {

        // Use real profile values; safe defaults only if a field was left blank
        float  w = (weight != null && weight > 0) ? weight : 70f;   // kg
        float  h = (height != null && height > 0) ? height : 170f;  // cm
        int    a = (age    != null && age    > 0) ? age    : 25;     // years

        // Gender-specific Mifflin-St Jeor constant
        double bmr;
        if ("FEMALE".equalsIgnoreCase(gender) || "F".equalsIgnoreCase(gender)) {
            bmr = (10.0 * w) + (6.25 * h) - (5.0 * a) - 161;
        } else {
            // MALE, OTHER, or null — use male formula
            bmr = (10.0 * w) + (6.25 * h) - (5.0 * a) + 5;
        }

        double tdee = bmr * getActivityMultiplier(activityLevel);

        // Goal-specific calorie adjustment
        double adjusted;
        if (goal == null) {
            adjusted = tdee;
        } else {
            switch (goal.toUpperCase()) {
                case "WEIGHT_LOSS":
                    // 500 kcal deficit → ~0.5 kg fat loss per week
                    adjusted = tdee - 500;
                    break;
                case "MUSCLE_GAIN":
                case "WEIGHT_GAIN":
                    // 300 kcal surplus → lean bulk, minimal fat gain
                    adjusted = tdee + 300;
                    break;
                case "MAINTAIN_FITNESS":
                case "ENDURANCE":
                case "FLEXIBILITY":
                default:
                    adjusted = tdee;
                    break;
            }
        }

        System.out.println("BMR=" + Math.round(bmr)
                + " TDEE=" + Math.round(tdee)
                + " Adjusted=" + Math.round(adjusted)
                + " (gender=" + gender + ", age=" + a
                + ", weight=" + w + "kg, height=" + h + "cm)");

        // Clamp: minimum safe calories, maximum realistic intake
        int result = (int) Math.round(adjusted);
        return Math.max(1400, Math.min(result, 4500));
    }

    private double getActivityMultiplier(String activityLevel) {
        if (activityLevel == null) return 1.55;
        switch (activityLevel.toUpperCase()) {
            case "SEDENTARY": return 1.2;
            case "LIGHT":     return 1.375;
            case "MODERATE":  return 1.55;
            case "ACTIVE":    return 1.725;
            case "VERY_ACTIVE": return 1.9;
            default:          return 1.55;
        }
    }

    // ── Food filtering ────────────────────────────────────────────────────
    // Uses keyword-matching so it works with any food name, not just exact names.

    private List<FoodLibrary> filterByPreference(List<FoodLibrary> foods, String preference) {
        if (preference == null) return foods;

        switch (preference.toUpperCase()) {

            case "VEGAN":
                // Exclude all animal products: meat, fish, dairy, eggs
                return foods.stream()
                        .filter(f -> !containsAny(f.getFoodName(),
                                "chicken", "beef", "salmon", "tuna", "shrimp", "turkey",
                                "lamb", "fish", "prawn", "cod", "steak", "jerky",
                                "egg", "omelette", "paneer", "cheese", "yogurt",
                                "milk", "mozzarella", "cottage", "whey", "ghee",
                                "butter", "cream"))
                        .collect(Collectors.toList());

            case "VEGETARIAN":
                // Exclude meat and fish only — dairy and eggs are fine
                return foods.stream()
                        .filter(f -> !containsAny(f.getFoodName(),
                                "chicken", "beef", "salmon", "tuna", "shrimp", "turkey",
                                "lamb", "fish", "prawn", "cod", "steak", "jerky"))
                        .collect(Collectors.toList());

            case "LOW_CARB":
                // Exclude foods where carbs > 25g per serving
                return foods.stream()
                        .filter(f -> f.getCarbsGrams() != null && f.getCarbsGrams() <= 25f)
                        .collect(Collectors.toList());

            case "KETO":
                // Very strict: carbs <= 10g per serving, fat > protein
                return foods.stream()
                        .filter(f -> f.getCarbsGrams() != null && f.getCarbsGrams() <= 10f
                                && f.getFatsGrams() != null && f.getProteinGrams() != null
                                && f.getFatsGrams() >= f.getProteinGrams() * 0.5f)
                        .collect(Collectors.toList());

            case "HIGH_PROTEIN":
                // At least 15g protein per serving
                return foods.stream()
                        .filter(f -> f.getProteinGrams() != null && f.getProteinGrams() >= 15f)
                        .collect(Collectors.toList());

            case "BALANCED":
            default:
                return foods; // No filter — all foods allowed
        }
    }

    /**
     * Case-insensitive check whether foodName contains ANY of the given keywords.
     */
    private boolean containsAny(String foodName, String... keywords) {
        if (foodName == null) return false;
        String lower = foodName.toLowerCase();
        for (String kw : keywords) {
            if (lower.contains(kw)) return true;
        }
        return false;
    }

    private List<FoodLibrary> filterByCategory(List<FoodLibrary> foods, String category) {
        return foods.stream()
                .filter(f -> category.equalsIgnoreCase(f.getCategory()))
                .collect(Collectors.toList());
    }

    private String formatGoalLabel(String goal) {
        if (goal == null) return "Custom";
        String[] words = goal.toLowerCase().replace("_", " ").split(" ");
        StringBuilder sb = new StringBuilder();
        for (String word : words) {
            if (sb.length() > 0) sb.append(" ");
            if (!word.isEmpty()) {
                sb.append(Character.toUpperCase(word.charAt(0)));
                sb.append(word.substring(1));
            }
        }
        return sb.toString();
    }
}