package com.vfit.modules.diet.service;

import com.vfit.modules.diet.dto.DietPlanDto;
import com.vfit.modules.diet.entity.DietPlan;
import com.vfit.modules.diet.entity.FoodLibrary;
import com.vfit.modules.diet.entity.Meal;
import com.vfit.modules.diet.repository.DietPlanRepository;
import com.vfit.modules.diet.repository.FoodLibraryRepository;
import com.vfit.modules.user.entity.Profile;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.ProfileRepository;
import com.vfit.modules.user.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

@Service
public class AutoDietGeneratorService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProfileRepository profileRepository;

    @Autowired
    private DietPlanRepository dietPlanRepository;

    @Autowired
    private FoodLibraryRepository foodLibraryRepository;

    @Autowired
    private DietService dietService;

    // UC-06: Auto-generate diet plan
    @Transactional
    public DietPlanDto generateDietPlan(Long userId) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        Profile profile = profileRepository.findByUser_UserId(userId)
                .orElseThrow(() -> new RuntimeException(
                        "Please complete your profile first"));

        if (profile.getFitnessGoal() == null || profile.getDietaryPreference() == null) {
            throw new RuntimeException(
                    "Fitness goal and dietary preference are required");
        }

        DietPlan plan = new DietPlan();
        plan.setUser(user);
        plan.setPlanName("Auto-Generated: " + profile.getFitnessGoal());
        plan.setDietType(profile.getDietaryPreference());
        plan.setScheduleCalendar("WEEKLY");
        plan.setIsAutoGenerated(true);

        // Calculate target calories based on goal
        int targetCalories = calculateTargetCalories(
                profile.getFitnessGoal(),
                profile.getWeight(),
                profile.getActivityLevel()
        );
        plan.setTargetCalories(targetCalories);

        System.out.println(" Generating diet for goal: " + profile.getFitnessGoal());
        System.out.println(" Diet preference: " + profile.getDietaryPreference());
        System.out.println(" Target calories: " + targetCalories);

        // Generate meals
        List<Meal> meals = generateMealsForGoal(
                plan,
                profile.getDietaryPreference(),
                targetCalories
        );

        if (meals.isEmpty()) {
            throw new RuntimeException("No foods available. Please contact admin.");
        }

        plan.setMeals(meals);
        DietPlan saved = dietPlanRepository.save(plan);

        return dietService.mapToDto(saved);
    }

    private List<Meal> generateMealsForGoal(DietPlan plan,
                                            String dietPreference,
                                            int targetCalories) {

        List<Meal> meals = new ArrayList<>();

        // Get foods from library
        List<FoodLibrary> foodLibrary = foodLibraryRepository.findAll();

        if (foodLibrary.isEmpty()) {
            throw new RuntimeException("Food library is empty");
        }

        System.out.println(" Found " + foodLibrary.size() + " foods in library");

        // Calculate calories per meal (3 meals per day, 7 days)
        int caloriesPerMeal = targetCalories / 3;

        String[] mealTypes = {"BREAKFAST", "LUNCH", "DINNER"};

        // Generate 7 days of meals
        for (int day = 1; day <= 7; day++) {
            for (String mealType : mealTypes) {
                int foodIndex = ((day - 1) * 3 + meals.size()) % foodLibrary.size();
                FoodLibrary food = foodLibrary.get(foodIndex);

                Meal meal = new Meal();
                meal.setDietPlan(plan);
                meal.setFood(food);
                meal.setMealType(mealType);
                meal.setDayOfWeek(day);
                meal.setCalories(food.getCaloriesPerServing());
                meal.setProteinGrams(food.getProteinGrams());
                meal.setCarbsGrams(food.getCarbsGrams());
                meal.setFatsGrams(food.getFatsGrams());

                meals.add(meal);

                System.out.println("  Day " + day + " - " + mealType + 
                        ": " + food.getFoodName() + 
                        " (" + food.getCaloriesPerServing() + " cal)");
            }
        }

        System.out.println(" Created " + meals.size() + " total meals");
        return meals;
    }

    private int calculateTargetCalories(String goal, Float weight, String activityLevel) {
        
        int baseCalories = 2000;

        // Adjust based on weight
        if (weight != null) {
            baseCalories = (int) (weight * 30);
        }

        // Adjust based on activity level
        if (activityLevel != null) {
            switch (activityLevel.toUpperCase()) {
                case "SEDENTARY":
                case "LOW":
                    baseCalories *= 1.2;
                    break;
                case "MODERATE":
                    baseCalories *= 1.55;
                    break;
                case "HIGH":
                case "VERY_HIGH":
                    baseCalories *= 1.9;
                    break;
            }
        }

        // Adjust based on goal
        if (goal != null) {
            switch (goal.toUpperCase()) {
                case "WEIGHT_LOSS":
                    baseCalories -= 500;
                    break;
                case "MUSCLE_GAIN":
                case "WEIGHT_GAIN":
                    baseCalories += 500;
                    break;
            }
        }

        return Math.max(1200, Math.min(baseCalories, 4000));
    }
}
