package com.vfit.modules.diet.service;

import com.vfit.modules.diet.dto.CreateDietPlanRequest;
import com.vfit.modules.diet.dto.DietPlanDto;
import com.vfit.modules.diet.dto.MealDto;
import com.vfit.modules.diet.entity.DietPlan;
import com.vfit.modules.diet.entity.FoodLibrary;
import com.vfit.modules.diet.entity.Meal;
import com.vfit.modules.diet.repository.DietPlanRepository;
import com.vfit.modules.diet.repository.FoodLibraryRepository;
import com.vfit.modules.user.entity.User;
import com.vfit.modules.user.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class DietService {

    @Autowired
    private DietPlanRepository dietPlanRepository;

    @Autowired
    private FoodLibraryRepository foodLibraryRepository;

    @Autowired
    private UserRepository userRepository;

    // UC-05: Get all diet plans
    @Transactional(readOnly = true)
    public List<DietPlanDto> getAllDietPlans(Long userId) {
        List<DietPlan> plans = dietPlanRepository.findByUser_UserId(userId);
        return plans.stream()
                .map(this::mapToDto)
                .collect(Collectors.toList());
    }

    // UC-05: Get single diet plan
    @Transactional(readOnly = true)
    public DietPlanDto getDietPlan(Long userId, Long dietPlanId) {
        DietPlan plan = dietPlanRepository
                .findByDietPlanIdAndUser_UserId(dietPlanId, userId)
                .orElseThrow(() -> new RuntimeException("Diet plan not found"));
        return mapToDto(plan);
    }

    // UC-05: Create manual diet plan
    @Transactional
    public DietPlanDto createDietPlan(Long userId, CreateDietPlanRequest request) {

        if (request.getPlanName() == null || request.getPlanName().trim().isEmpty()) {
            throw new RuntimeException("Plan name is required");
        }

        if (request.getMeals() == null || request.getMeals().isEmpty()) {
            throw new RuntimeException("At least one meal is required");
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));

        DietPlan plan = new DietPlan();
        plan.setUser(user);
        plan.setPlanName(request.getPlanName());
        plan.setDietType(request.getDietType());
        plan.setScheduleCalendar(request.getScheduleCalendar());
        plan.setTargetCalories(request.getTargetCalories());
        plan.setIsAutoGenerated(false);

        List<Meal> meals = new ArrayList<>();
        for (MealDto dto : request.getMeals()) {
            Meal meal = new Meal();
            meal.setDietPlan(plan);

            if (dto.getFoodId() != null) {
                FoodLibrary food = foodLibraryRepository
                        .findById(dto.getFoodId())
                        .orElseThrow(() -> new RuntimeException("Food not found in library"));
                meal.setFood(food);
            }

            meal.setMealType(dto.getMealType());
            meal.setCalories(dto.getCalories());
            meal.setProteinGrams(dto.getProteinGrams());
            meal.setCarbsGrams(dto.getCarbsGrams());
            meal.setFatsGrams(dto.getFatsGrams());
            meal.setDayOfWeek(dto.getDayOfWeek());
            meals.add(meal);
        }

        plan.setMeals(meals);
        DietPlan saved = dietPlanRepository.save(plan);
        return mapToDto(saved);
    }

    // UC-05: Update diet plan
    @Transactional
    public DietPlanDto updateDietPlan(Long userId, Long dietPlanId,
                                      CreateDietPlanRequest request) {

        DietPlan plan = dietPlanRepository
                .findByDietPlanIdAndUser_UserId(dietPlanId, userId)
                .orElseThrow(() -> new RuntimeException("Diet plan not found"));

        if (request.getPlanName() != null) {
            plan.setPlanName(request.getPlanName());
        }
        if (request.getDietType() != null) {
            plan.setDietType(request.getDietType());
        }
        if (request.getScheduleCalendar() != null) {
            plan.setScheduleCalendar(request.getScheduleCalendar());
        }
        if (request.getTargetCalories() != null) {
            plan.setTargetCalories(request.getTargetCalories());
        }

        if (request.getMeals() != null) {
            plan.getMeals().clear();

            List<Meal> meals = new ArrayList<>();
            for (MealDto dto : request.getMeals()) {
                Meal meal = new Meal();
                meal.setDietPlan(plan);

                if (dto.getFoodId() != null) {
                    FoodLibrary food = foodLibraryRepository
                            .findById(dto.getFoodId())
                            .orElseThrow(() -> new RuntimeException("Food not found"));
                    meal.setFood(food);
                }

                meal.setMealType(dto.getMealType());
                meal.setCalories(dto.getCalories());
                meal.setProteinGrams(dto.getProteinGrams());
                meal.setCarbsGrams(dto.getCarbsGrams());
                meal.setFatsGrams(dto.getFatsGrams());
                meal.setDayOfWeek(dto.getDayOfWeek());
                meals.add(meal);
            }

            plan.getMeals().addAll(meals);
        }

        DietPlan updated = dietPlanRepository.save(plan);
        return mapToDto(updated);
    }

    // UC-05: Delete diet plan
    @Transactional
    public void deleteDietPlan(Long userId, Long dietPlanId) {
        DietPlan plan = dietPlanRepository
                .findByDietPlanIdAndUser_UserId(dietPlanId, userId)
                .orElseThrow(() -> new RuntimeException("Diet plan not found"));

        dietPlanRepository.delete(plan);
    }

    // Get food library
    public List<FoodLibrary> getAllFoods() {
        return foodLibraryRepository.findAll();
    }

    // Map entity to DTO - PUBLIC for auto-generator
    public DietPlanDto mapToDto(DietPlan plan) {
        DietPlanDto dto = new DietPlanDto();
        dto.setDietPlanId(plan.getDietPlanId());
        dto.setPlanName(plan.getPlanName());
        dto.setDietType(plan.getDietType());
        dto.setScheduleCalendar(plan.getScheduleCalendar());
        dto.setTargetCalories(plan.getTargetCalories());
        dto.setIsAutoGenerated(plan.getIsAutoGenerated());
        dto.setCreatedAt(plan.getCreatedAt());

        List<MealDto> mealDtos = plan.getMeals().stream()
                .map(this::mapMealToDto)
                .collect(Collectors.toList());
        dto.setMeals(mealDtos);

        return dto;
    }

    public MealDto mapMealToDto(Meal meal) {
        MealDto dto = new MealDto();
        dto.setMealId(meal.getMealId());

        if (meal.getFood() != null) {
            dto.setFoodId(meal.getFood().getFoodId());
            dto.setFoodName(meal.getFood().getFoodName());
            dto.setServingSize(meal.getFood().getServingSize());
        }

        dto.setMealType(meal.getMealType());
        dto.setCalories(meal.getCalories());
        dto.setProteinGrams(meal.getProteinGrams());
        dto.setCarbsGrams(meal.getCarbsGrams());
        dto.setFatsGrams(meal.getFatsGrams());
        dto.setDayOfWeek(meal.getDayOfWeek());

        return dto;
    }
}